/* ============================================================
 BANCO MCQ — CASO EPO DEL AGUACATE HASS (México, 2025)
 Evaluación 2BGU · Economía IB NM · Logos Academy
 Ejes:
   A) ¿Qué condiciona la elasticidad? (determinantes; el factor
      que aborda la noticia: tiempo de cosecha e inventarios).
   B) ¿La oferta inelástica es ventaja o vulnerabilidad?
      (productor, consumidor, gobierno, economía en su conjunto).
   C) Análisis tipo presentación (misma señal, diagrama 40 %,
      vivienda con evidencia numérica) + cálculo del taller.
   D) Conceptos clave (los 9 de IB) integrados.
 Reglas: opciones balanceadas, correcta nunca la única más larga,
 distractores = errores reales, sin símbolos IA, terminología IB,
 explicaciones breves con datos del caso.
 ============================================================ */
const QUESTION_BANK = [
 // ========== A · P1 DEL TALLER: CÁLCULO E INTERPRETACIÓN ==========
 {topic:"P1 · Cálculo", unit:"Taller P1", concept:"—", syllabus:"Fórmula EPO",
  scenario:"Entre junio y julio de 2025 el precio mayorista del aguacate pasó de MXN 100 a MXN 120 por kilogramo. El grupo de productores de Michoacán con inventario en frío elevó la cantidad colocada de 2.500 a 2.575 toneladas.",
  question:"Siguiendo el procedimiento del taller (variaciones porcentuales sobre los valores de junio), la elasticidad precio de la oferta del grupo es:",
  options:["0,15: la cantidad ofrecida creció 3 % y el precio subió 20 %.",
           "0,17: se usan los valores de julio como base del cálculo.",
           "3,75: se dividen los cambios absolutos sin porcentajes.",
           "6,67: se invierte la fórmula: cambio del precio entre cambio de cantidad."],
  answer:0,
  explanation:"Variación de la cantidad: (2.575 - 2.500) / 2.500 = 3 %. Variación del precio: (120 - 100) / 100 = 20 %. EPO = 3 % / 20 % = 0,15. La presentación recomienda el método del punto medio, que daría 0,16; el taller pide base inicial, por eso el valor es 0,15."},
 {topic:"P1 · Clasificación", unit:"Taller P1", concept:"—", syllabus:"Valores de la EPO",
  scenario:"El valor de la elasticidad precio de la oferta del grupo de Michoacán fue 0,15 entre junio y julio de 2025.",
  question:"Con ese valor, la oferta del grupo de productores se clasifica como:",
  options:["Elástica: la cantidad ofrecida responde con fuerza al precio.",
           "Inelástica: la cantidad ofrecida responde poco al precio.",
           "Unitaria: la cantidad ofrecida responde en la misma proporción.",
           "Perfectamente elástica: cualquier variación del precio altera la oferta."],
  answer:1,
  explanation:"Como 0,15 es menor que 1, la cantidad ofrecida creció menos que proporcionalmente al precio: la oferta es inelástica. En el diagrama de la presentación, corresponde a una curva empinada."},
 {topic:"P1 · Interpretación", unit:"Taller P1", concept:"—", syllabus:"Capacidad de respuesta",
  scenario:"El grupo de Michoacán elevó su cantidad colocada de 2.500 a 2.575 toneladas cuando el precio pasó de MXN 100 a MXN 120. La mayoría de los huertos ya no tenía fruta.",
  question:"El valor de 0,15 revela que la capacidad de respuesta de esos productores fue:",
  options:["Amplia: la cantidad ofrecida creció más que el precio y aprovechó el alza para vender más fruta.",
           "Proporcional: la cantidad ofrecida subió en la misma medida que el precio, sin más.",
           "Nula: la cantidad ofrecida no cambió pese al alza, porque no había fruta disponible.",
           "Limitada: solo pudieron ofrecer más porque tenían inventario en frío y lotes adelantados."],
  answer:3,
  explanation:"El valor bajo (0,15) revela poca capacidad de respuesta: solo pudieron ofrecer 3 % más gracias al inventario en frío y a los lotes adelantados. Sin esos recursos, no habrían podido aprovechar el alza, como les pasó a los demás huertos."},

 // ========== A · ¿QUÉ CONDICIONA LA ELASTICIDAD? (DETERMINANTES) ==========
 {topic:"Determinante · Tiempo", unit:"Taller P2/P3", concept:"—", syllabus:"Factor de la noticia",
  scenario:"La mayoría de los huertos ya había terminado el corte principal en julio. Aunque el precio subió a MXN 120, no tenían fruta que ofrecer hasta que se reabra la temporada, en noviembre.",
  question:"¿Qué determinante de la EPO explica mejor que esos huertos no pudieran responder al alza?",
  options:["El tiempo de respuesta: la fruta no estará lista hasta la próxima temporada de cosecha.",
           "La disponibilidad de inventarios: la fruta almacenada se echó a perder durante el corte.",
           "La capacidad ociosa: los huertos operaban con toda su maquinaria en uso permanente.",
           "La complejidad del proceso: el empaque del aguacate requiere más tiempo que otros cultivos."],
  answer:0,
  explanation:"Aunque el precio suba, la fruta no aparece hasta noviembre: el tiempo de producción es el determinante más importante (presentación, sección 05). La estacionalidad de la cosecha hace inelástica la oferta en temporada baja."},
 {topic:"Determinante · Misma señal", unit:"Taller P2/P3", concept:"—", syllabus:"Decisión frente a la misma señal",
  scenario:"Todos los productores recibieron la misma señal: el precio pasó de MXN 100 a MXN 120. El grupo con inventario en frío elevó su cantidad colocada en 75 toneladas; los huertos que ya habían terminado el corte no pudieron ofrecer nada más.",
  question:"¿Qué factor determinante explica que, ante la misma señal de precio, un grupo responda y el otro no?",
  options:["El tiempo de respuesta: unos ciclos de cosecha maduran más rápido que otros huertos.",
           "La disponibilidad de inventarios: solo el grupo con frío tenía fruta almacenada para vender.",
           "La movilidad de los factores: unos productores usan más trabajo y otros más capital para producir aguacate.",
           "La complejidad del proceso: el empaque del aguacate es más lento en algunos huertos."],
  answer:1,
  explanation:"El factor que diferencia a ambos grupos es el inventario en frío: el grupo podía vender fruta ya almacenada, mientras los demás no tenían producto hasta la próxima cosecha. El tiempo afecta a todos por igual, porque la temporada terminó para todo el mercado."},
 {topic:"Determinante · Capacidad ociosa", unit:"Presentación", concept:"—", syllabus:"Ejemplo quesería vs estancia",
  scenario:"En la presentación, una quesería artesanal con tanques ociosos aumenta su producción 45 % ante un alza del 25 % en el precio de la leche. Una estancia ganadera solo puede aumentar 4 %, porque el ganado tarda dos años en crecer y la leche fresca no se puede almacenar.",
  question:"¿Qué determinante explica principalmente la capacidad de respuesta de la quesería?",
  options:["La capacidad ociosa: usaba parte de su planta y podía activar tanques sin usar de inmediato.",
           "La disponibilidad de inventarios: la quesería almacenaba leche en tanques durante meses.",
           "La movilidad de los factores: el capital de la estancia se puede mover entre sectores con facilidad.",
           "La complejidad del proceso: la estancia tiene un proceso de producción más complejo."],
  answer:0,
  explanation:"La quesería tenía tanques de fermentación sin usar y podía contratar un ayudante temporal: capacidad ociosa y mano de obra móvil. La estancia enfrenta tiempo de producción (dos años) y un bien perecedero (leche fresca), que son sus propios límites."},
 {topic:"Determinante · Tiempo (CP vs LP)", unit:"Taller P3", concept:"Cambio", syllabus:"Corto plazo vs largo plazo",
  scenario:"La EPO del mercado fue baja en julio (temporada cerrada) y será mayor en noviembre, cuando se reabra la cosecha y haya más fruta disponible.",
  question:"Este cambio entre temporadas muestra que la elasticidad precio de la oferta:",
  options:["Es una propiedad permanente de cada bien, idéntica en todo momento y mercado.",
           "Depende solo del precio del bien en el mercado, sin importar el tiempo.",
           "No es un valor fijo: depende del tiempo y de la capacidad de respuesta.",
           "Se calcula únicamente con datos oficiales del gobierno nacional."],
  answer:2,
  explanation:"La elasticidad no es fija: en julio la oferta fue inelástica porque la cosecha había terminado; en noviembre, con más fruta disponible, la capacidad de respuesta aumenta. El tiempo es el determinante más importante y las condiciones cambian entre temporadas."},

 // ========== B · ¿LA OFERTA INELÁSTICA ES VENTAJA O VULNERABILIDAD? ==========
 {topic:"Ventaja o vulnerabilidad · Productor", unit:"Taller P2", concept:"—", syllabus:"Perspectiva del productor",
  scenario:"En julio, la EPO del grupo de Michoacán fue 0,15 (inelástica) y el precio mayorista alcanzó MXN 120, el nivel más alto del año.",
  question:"Para ese grupo, la inelasticidad de su oferta resultó una ventaja en julio porque:",
  options:["Pudo vender su fruta almacenada al precio alto sin expandir mucho la producción.",
           "Pudo reducir su cantidad ofrecida para hacer subir aún más el precio del mercado.",
           "Los consumidores compraron más cantidad al precio alto, aumentando sus ingresos.",
           "El gobierno le garantizó un precio mínimo superior al precio del mercado mayorista."],
  answer:0,
  explanation:"Con oferta inelástica, el grupo no necesitó invertir en expandir producción: su inventario en frío y sus lotes adelantados le permitieron colocar 2.575 toneladas al precio alto. La presentación lo llama ingresos extraordinarios sin expandir la producción."},
 {topic:"Ventaja o vulnerabilidad · Productor", unit:"Taller P3", concept:"—", syllabus:"Perspectiva del productor",
  scenario:"En noviembre se reabre la cosecha y el precio mayorista cae 25 % respecto del pico de julio. La EPO del grupo sigue siendo baja en el corto plazo.",
  question:"En noviembre, la inelasticidad de la oferta se convierte en vulnerabilidad porque el grupo:",
  options:["No puede reducir su cantidad ofrecida con rapidez y sus ingresos caen con el precio.",
           "Puede aumentar su producción para compensar la caída del precio con más volumen.",
           "Pierde todo su inventario en frío, que ya no puede venderse en ninguna temporada.",
           "Debe pagar impuestos mayores por la reapertura de la temporada de cosecha en noviembre."],
  answer:0,
  explanation:"La inelasticidad significa poca capacidad de ajuste: si el precio cae 25 %, la cantidad ofrecida apenas se reduce y los ingresos caen casi en la misma proporción. Es la contracara de la ventaja de julio, como muestra la sección 06 de la presentación."},
 {topic:"Ventaja o vulnerabilidad · Consumidor", unit:"Taller P2", concept:"Bienestar económico", syllabus:"Perspectiva del consumidor",
  scenario:"El precio mayorista del aguacate llegó a MXN 120 por kilogramo y la inflación anual del producto alcanzó 14,17 %. La oferta en temporada baja es inelástica.",
  question:"Para los consumidores mexicanos, la oferta inelástica del aguacate en temporada baja es una vulnerabilidad porque:",
  options:["La escasez de fruta eleva el precio y los hogares absorben el alza sin sustituto inmediato.",
           "La cantidad ofrecida aumenta mucho, inundando el mercado y abaratando el producto.",
           "Los productores exportan menos fruta, dejando más producto disponible para el consumo local.",
           "El gobierno fija el precio por debajo del equilibrio, generando excedente de oferta."],
  answer:0,
  explanation:"Con oferta inelástica y demanda sostenida, el ajuste recae en el precio: sube hasta MXN 120 y el hogar no encuentra sustituto inmediato. El poder de compra cae: eso afecta el bienestar económico, como lo describe la prensa al llamarlo producto de lujo."},
 {topic:"Ventaja o vulnerabilidad · Gobierno", unit:"Taller P4", concept:"Intervención", syllabus:"Perspectiva del gobierno",
  scenario:"La inflación anual del aguacate llegó a 14,17 % y la prensa lo llama producto de lujo. El gobierno estudia medidas para contener el precio en temporada baja.",
  question:"Para el gobierno, la oferta inelástica de un alimento básico representa principalmente:",
  options:["Inflación de alimentos difícil de frenar, porque la oferta no responde con rapidez.",
           "Una oportunidad de recaudar más impuestos sin afectar a ningún grupo social.",
           "Un mercado sin problemas, porque el precio alto beneficia a todos los productores.",
           "Una razón para eliminar todo subsidio agrícola y dejar actuar libremente al mercado."],
  answer:0,
  explanation:"Cuando la oferta no responde, la política monetaria pierde eficacia para controlar la inflación de alimentos. El gobierno puede intervenir (subsidios, importaciones, reservas), como evalúa el taller: es el concepto clave de intervención, con trade-offs entre objetivos."},
 {topic:"Ventaja o vulnerabilidad · Economía", unit:"Taller P2", concept:"Eficiencia", syllabus:"Perspectiva de la economía en su conjunto",
  scenario:"La oferta inelástica del aguacate amplificó el alza de precios: con poca variación de la producción, el precio pasó de MXN 100 a MXN 120 en un mes.",
  question:"Para la economía en su conjunto, una oferta inelástica en bienes básicos genera principalmente:",
  options:["Volatilidad de precios y una asignación de recursos menos eficiente ante los shocks.",
           "Un crecimiento económico más rápido, porque los precios altos atraen inversión externa.",
           "Una distribución más equitativa del ingreso entre los sectores productivos.",
           "Una reducción permanente de la inflación en todos los mercados de alimentos."],
  answer:0,
  explanation:"Cuando la oferta no responde a la señal de precio, el ajuste recae sobre los precios: hay volatilidad y los recursos no se mueven hacia donde la sociedad más los valora (ineficiencia asignativa), como explica la presentación en la sección 06."},

 // ========== C · ANÁLISIS TIPO PRESENTACIÓN ==========
 {topic:"Análisis · Diagrama", unit:"Presentación", concept:"—", syllabus:"Diagrama con dos curvas",
  scenario:"En el diagrama de la presentación, dos curvas de oferta parten del mismo punto (Q1, P1): una elástica (plana) y otra inelástica (empinada). El precio aumenta 40 %.",
  question:"Al comparar la cantidad ofrecida en cada curva después del aumento, se observa que:",
  options:["Aumenta más en la curva elástica, porque es más plana y responde con más intensidad al precio.",
           "Aumenta igual en ambas, porque las dos curvas parten del mismo punto inicial.",
           "Aumenta más en la curva inelástica, porque es más empinada y transmite mejor la señal del precio.",
           "No cambia en ninguna curva, porque el punto de partida es el mismo para las dos."],
  answer:0,
  explanation:"La curva elástica (plana) muestra una gran variación de la cantidad ofrecida ante el mismo cambio de precio; la inelástica (empinada) casi no responde. La brecha horizontal entre las dos cantidades finales es la diferencia de respuesta, como en el diagrama interactivo."},
 {topic:"Análisis · Vivienda", unit:"Presentación", concept:"—", syllabus:"Evidencia numérica",
  scenario:"Según la presentación, la vivienda urbana tiene una EPO de aproximadamente 0,3: el precio subió 120 % y la cantidad ofrecida solo aumentó 36 %.",
  question:"Con esa evidencia numérica, para quienes buscan vivienda la oferta inelástica es una vulnerabilidad porque:",
  options:["El precio sube mucho más que la cantidad ofrecida, reduciendo el acceso a la vivienda.",
           "La cantidad ofrecida crece rápido y el mercado se satura de oferta disponible.",
           "Los precios se mantienen estables a largo plazo porque la oferta no responde a los cambios del mercado.",
           "El gobierno puede recaudar más impuestos a la propiedad sin costos sociales."],
  answer:0,
  explanation:"Con EPO 0,3, un aumento de 120 % en el precio solo genera 36 % más de oferta: el precio sube mucho más que la cantidad disponible y el acceso a la vivienda se reduce. Es la misma lógica del aguacate: escasez y caída del bienestar."},
 {topic:"Análisis · Estrategia", unit:"Taller P3", concept:"—", syllabus:"Uso de la EPO en decisiones",
  scenario:"En noviembre se reabre la temporada fuerte de cosecha y el precio mayorista cae 25 % respecto del pico de julio. La EPO del grupo de Michoacán fue 0,15 (inelástica).",
  question:"Ante ese escenario, ¿qué estrategia es más coherente con el valor de elasticidad obtenido?",
  options:["Vender toda la cosecha en noviembre, cuando el precio es más bajo, para asegurar ingresos rápidos.",
           "Almacenar en frío parte de la cosecha para venderla en temporada baja, cuando escasee.",
           "Expandir de inmediato las plantaciones para duplicar la producción en el mismo mes.",
           "Fijar un precio mínimo obligatorio por encima del precio de mercado para todos los compradores."],
  answer:1,
  explanation:"Con EPO 0,15 el grupo no puede ajustar su cantidad: su mejor opción es el arbitraje temporal, guardar en frío parte de la cosecha para venderla cuando escasee y el precio suba. La limitación es el costo y la capacidad de almacenamiento."},
 {topic:"Análisis · Política pública", unit:"Taller P4", concept:"—", syllabus:"Corto plazo vs largo plazo",
  scenario:"En plena temporada baja, el gobierno evalúa dos medidas para contener el precio del aguacate: subsidiar la producción nacional o abrir las importaciones.",
  question:"¿Qué medida agrega oferta al mercado con mayor rapidez en el corto plazo?",
  options:["Subsidiar la producción nacional, que aumenta la fruta cuando madure la próxima cosecha.",
           "Reducir el impuesto al consumo, que aumenta la demanda de los compradores.",
           "Abrir las importaciones, que suman fruta disponible al mercado de inmediato.",
           "Fijar un precio máximo por debajo del precio de equilibrio del mercado."],
  answer:2,
  explanation:"En el corto plazo la oferta interna es inelástica: la fruta ya está cortada. Las importaciones agregan oferta de inmediato y frenan el precio. El subsidio a la producción actúa recién cuando madure la próxima cosecha (largo plazo)."},

 // ========== D · CONCEPTOS CLAVE (9 DE IB) ==========
 {topic:"Concepto clave · Escasez", unit:"Taller P2", concept:"Escasez", syllabus:"Conceptos clave IB",
  scenario:"Al terminar el corte principal de la temporada, la fruta disponible se redujo de forma abrupta mientras el consumo interno y la demanda de exportación se mantuvieron sostenidos.",
  question:"El precio subió hasta MXN 120 porque la fruta disponible era limitada frente a una demanda sostenida. ¿Qué concepto clave describe esta situación?",
  options:["Escasez: la cantidad disponible es limitada frente a las necesidades.",
           "Cambio: las preferencias y las condiciones del mercado evolucionan con el tiempo.",
           "Intervención: el gobierno fijó el precio mayorista del aguacate.",
           "Interdependencia: los productores dependen de insumos importados."],
  answer:0,
  explanation:"Hay escasez relativa: la fruta disponible cayó al cerrar la temporada mientras la demanda se mantenía. El precio subió hasta MXN 120 como señal de esa limitación. No hubo intervención del gobierno: el precio lo fijó el mercado."},
 {topic:"Concepto clave · Elección", unit:"Taller P3", concept:"Elección", syllabus:"Conceptos clave IB",
  scenario:"Los productores con inventario deben decidir entre vender ahora al precio de julio o guardar la fruta en frío para venderla en temporada baja, cuando escasee.",
  question:"Cada opción tiene beneficios y costos; elegir una implica renunciar a la otra. ¿Qué concepto clave ilustra este dilema?",
  options:["Elección: los agentes deciden entre alternativas con costo de oportunidad.",
           "Escasez: los recursos disponibles son limitados para todas las personas.",
           "Equidad: los beneficios se reparten de forma justa entre todos los productores del mercado.",
           "Eficiencia: el mercado asigna los recursos al mejor uso posible para la sociedad."],
  answer:0,
  explanation:"El dilema entre vender ahora o almacenar es una elección: cada alternativa tiene beneficios y costos, y elegir una implica renunciar a la otra (costo de oportunidad). Es el concepto clave de elección."},
 {topic:"Concepto clave · Equidad", unit:"Taller P2", concept:"Equidad", syllabus:"Conceptos clave IB",
  scenario:"El aguacate pasó de un alimento común a un producto de lujo. Los hogares de menores ingresos destinan una mayor parte de su presupuesto a alimentos, y el alza los golpea con más fuerza.",
  question:"El impacto desigual del alza según el nivel de ingresos ilustra el concepto clave de:",
  options:["Equidad: el efecto del alza no se reparte de forma justa entre los hogares.",
           "Eficiencia: los recursos productivos se asignan al mejor uso alternativo en el mercado.",
           "Escasez: la fruta disponible es limitada frente a la demanda sostenida.",
           "Cambio: las condiciones y las preferencias del mercado evolucionan con el tiempo."],
  answer:0,
  explanation:"Equidad se refiere a la distribución justa de costos y beneficios. El alza golpea con más fuerza a los hogares de menores ingresos porque los alimentos pesan más en su presupuesto, como ocurre con el aguacate visto como producto de lujo."},
 {topic:"Concepto clave · Interdependencia", unit:"Taller P2", concept:"Interdependencia", syllabus:"Conceptos clave IB",
  scenario:"El consumo interno mexicano y la demanda de exportación compiten por la misma producción de aguacate: si la exportación crece, queda menos fruta para el mercado local.",
  question:"Esta conexión entre el mercado interno y el de exportación ilustra el concepto clave de:",
  options:["Cambio: las condiciones y las preferencias del mercado evolucionan con el tiempo.",
           "Interdependencia: los mercados se afectan mutuamente a través del comercio.",
           "Escasez: los recursos productivos son limitados en todo mercado.",
           "Intervención: el gobierno regula el comercio internacional del bien."],
  answer:1,
  explanation:"El mercado interno y la exportación compiten por la misma producción: son interdependientes. Si crece la demanda externa, queda menos fruta para el consumo local, y viceversa."},
 {topic:"Concepto clave · Sostenibilidad", unit:"Taller P4", concept:"Sostenibilidad", syllabus:"Conceptos clave IB",
  scenario:"El precio alto de julio incentiva a algunos productores a adelantar los cortes y dañar árboles jóvenes para aprovechar la oportunidad de venta.",
  question:"Si esta práctica se generaliza, ¿qué concepto clave se pone en riesgo?",
  options:["Eficiencia: los recursos se asignan al mejor uso alternativo.",
           "Sostenibilidad: la capacidad de producir en el futuro se reduce.",
           "Cambio: las condiciones del mercado evolucionan con el tiempo.",
           "Equidad: el acceso al aguacate se distribuye de forma desigual entre hogares."],
  answer:1,
  explanation:"Adelantar cortes y dañar árboles jóvenes reduce la producción futura: se sacrifica la capacidad de producir en el largo plazo. La sostenibilidad se refiere a mantener la producción a lo largo del tiempo."},
 {topic:"Concepto clave · Eficiencia", unit:"Taller P2", concept:"Eficiencia", syllabus:"Conceptos clave IB",
  scenario:"El alza del precio funciona como una señal: solo los productores con inventario y capacidad de respuesta aumentan su producción, y los recursos quedan en manos de quienes pueden usarlos mejor.",
  question:"La función del precio como señal que orienta la asignación de recursos se relaciona con el concepto clave de:",
  options:["Eficiencia: el mercado asigna los recursos hacia sus usos más valorados.",
           "Equidad: los beneficios del mercado se reparten de forma justa entre los agentes.",
           "Intervención: el Estado participa para corregir fallas del mercado.",
           "Bienestar económico: los hogares mantienen su poder de compra."],
  answer:0,
  explanation:"Los precios transmiten información: el alza indica que conviene producir más, y solo quienes pueden responder lo hacen. Esa función de señal orienta la asignación de recursos (eficiencia)."},
 // ========== AMPLIACIÓN DEL BANCO (31 preguntas) ==========
 {topic:"P1 · Cálculo", unit:"Taller P1", concept:"—", syllabus:"Método del punto medio",
  scenario:"Entre junio y julio de 2025 el precio del aguacate pasó de MXN 100 a MXN 120 y el grupo de Michoacán elevó su cantidad colocada de 2.500 a 2.575 toneladas.",
  question:"Usando el método del punto medio que recomienda la presentación, la elasticidad precio de la oferta del grupo es:",
  options:["0,16: se usa el promedio de los valores inicial y final como base.",
           "0,15: se usan los valores iniciales de junio como base del cálculo.",
           "0,17: se usan los valores finales de julio como base del cálculo.",
           "6,67: se invierte la fórmula: cambio del precio entre cambio de cantidad."],
  answer:0,
  explanation:"Punto medio: variación de la cantidad = 75 / 2.537,5 = 2,96 %; variación del precio = 20 / 110 = 18,18 %. EPO = 2,96 / 18,18 = 0,16. El taller pide base inicial (0,15); la presentación recomienda el punto medio."},
 {topic:"P1 · Cálculo", unit:"Taller P1", concept:"—", syllabus:"Variación porcentual",
  scenario:"El grupo de productores de Michoacán elevó su cantidad colocada de 2.500 a 2.575 toneladas entre junio y julio de 2025.",
  question:"La variación porcentual de la cantidad ofrecida del grupo fue:",
  options:["3 %: el aumento de 75 toneladas se divide entre las 2.500 iniciales.",
           "2,9 %: el aumento se divide entre las 2.575 toneladas finales del mes.",
           "20 %: es la misma variación porcentual del precio del aguacate.",
           "75 %: el aumento se expresa en toneladas, no en porcentaje."],
  answer:0,
  explanation:"Variación porcentual sobre el valor inicial: 75 / 2.500 = 3 %. Si se usara la base final daría 2,9 %, y el 20 % corresponde al precio, no a la cantidad."},
 {topic:"Determinante · Complejidad", unit:"Presentación", concept:"—", syllabus:"Complejidad del proceso productivo",
  scenario:"En la presentación, un avión comercial tarda unos 18 meses en producirse y el pan fresco se elabora en horas.",
  question:"¿Qué determinante de la EPO explica la diferencia de respuesta entre ambos bienes?",
  options:["La complejidad del proceso: el avión exige producción larga, especializada y de capital intensivo.",
           "La disponibilidad de inventarios: el pan se almacena meses y el avión no se puede guardar.",
           "La movilidad de los factores: los trabajadores del pan son más difíciles de contratar.",
           "El tiempo de respuesta: el avión se produce en pocas horas y el pan tarda 18 meses en estar listo."],
  answer:0,
  explanation:"Los bienes con procesos largos, tecnología especializada y capital intensivo tienen oferta inelástica (aviones); los de producción sencilla y rápida, oferta elástica (pan). Es el determinante de la complejidad del proceso."},
 {topic:"Determinante · Inventarios", unit:"Taller P2", concept:"—", syllabus:"Bienes perecederos",
  scenario:"El aguacate fresco madura rápido y, sin frío, se echa a perder en pocos días. En temporada baja, la mayoría de los productores no puede guardar fruta para venderla después.",
  question:"¿Cómo afecta esta característica a la elasticidad precio de la oferta del aguacate en el corto plazo?",
  options:["La reduce: sin posibilidad de almacenar, la cantidad ofrecida apenas responde al precio.",
           "La aumenta: los productores guardan fruta en cámaras para venderla cuando el precio suba.",
           "No la afecta: la elasticidad depende solo del nivel del precio del bien.",
           "La vuelve infinita: el producto se vende al precio que sea con tal de no perderlo."],
  answer:0,
  explanation:"Los bienes perecederos ofrecen poca posibilidad de almacenaje, así que la oferta responde poco al precio: EPO baja. El grupo del caso pudo responder justamente porque tenía cámaras de frío (inventario)."},
 {topic:"Determinante · Tiempo (LP)", unit:"Presentación", concept:"Cambio", syllabus:"Largo plazo estructural",
  scenario:"En el largo plazo, los productores de aguacate pueden plantar más árboles, ampliar sus huertos y construir más cámaras de frío.",
  question:"Por eso, la elasticidad precio de la oferta del aguacate en el largo plazo:",
  options:["Es mayor que en el corto plazo, porque los productores ajustan todos sus factores.",
           "Es menor que en el corto plazo, porque los árboles tardan varios años en producir.",
           "Es igual, porque la elasticidad no cambia con el paso del tiempo.",
           "Depende solo del precio internacional del aguacate en los mercados de exportación."],
  answer:0,
  explanation:"En el largo plazo todos los factores se pueden ajustar (plantar, ampliar, almacenar), así que la oferta se vuelve más elástica. En el corto plazo la fruta ya está cortada y no hay nada que hacer."},
 {topic:"Análisis · Diagrama", unit:"Presentación", concept:"—", syllabus:"Lectura de pendiente",
  scenario:"En el diagrama de la presentación, la curva de oferta inelástica se dibuja empinada (casi vertical) y la elástica plana (casi horizontal).",
  question:"La pendiente empinada de la curva inelástica representa que:",
  options:["Un cambio grande del precio produce un cambio pequeño en la cantidad ofrecida.",
           "Un cambio pequeño del precio produce un cambio grande en la cantidad ofrecida.",
           "El precio no cambia aunque la cantidad ofrecida aumente o disminuya.",
           "La cantidad ofrecida no depende del precio en ningún horizonte de tiempo."],
  answer:0,
  explanation:"Una curva empinada muestra poca respuesta de la cantidad ofrecida ante cambios del precio: por eso su EPO es menor que 1. La curva plana (elástica) muestra lo contrario."},
 {topic:"Análisis · Precio máximo", unit:"Presentación", concept:"Intervención", syllabus:"Intervención del gobierno",
  scenario:"La presentación menciona que el gobierno puede intervenir con precios máximos. En plena temporada baja, fija un precio máximo por debajo del equilibrio del mercado del aguacate.",
  question:"El resultado esperado de esa medida es:",
  options:["Escasez: la cantidad demandada supera a la cantidad ofrecida al precio fijado.",
           "Excedente: la cantidad ofrecida supera a la cantidad demandada al precio fijado.",
           "Equilibrio: el precio máximo coincide con el precio de equilibrio del mercado.",
           "Más producción: los productores aumentan su oferta para vender al precio fijado."],
  answer:0,
  explanation:"Con un precio máximo por debajo del equilibrio, la cantidad demandada aumenta y la ofrecida disminuye: se genera escasez. Es una intervención con efectos secundarios, como advierte la presentación."},
 {topic:"Ventaja o vulnerabilidad · Consumidor", unit:"Presentación", concept:"Bienestar económico", syllabus:"Evidencia numérica",
  scenario:"Según la presentación, durante la pandemia las vacunas tuvieron una EPO de aproximadamente 0,2: la producción no pudo crecer con rapidez ante la demanda global.",
  question:"Con esa oferta inelástica, ¿qué consecuencia se observó para los consumidores?",
  options:["Precios altos y acceso limitado, sobre todo en los países en desarrollo.",
           "Precios bajos y oferta abundante en todos los mercados del mundo entero.",
           "Producción inmediata suficiente para toda la población mundial.",
           "Precios estables porque la oferta no respondió a la demanda."],
  answer:0,
  explanation:"Con EPO 0,2 el ajuste recayó en el precio (hasta USD 40 por dosis) y el acceso fue desigual: los países en desarrollo esperaron más. Es la vulnerabilidad del consumidor ante oferta inelástica."},
 {topic:"Ventaja o vulnerabilidad · Productor", unit:"Presentación", concept:"—", syllabus:"Evidencia numérica",
  scenario:"En 2020 el precio del barril de petróleo cayó 65 % y la oferta mundial solo se redujo 8 % (EPO aproximada de 0,12), según la presentación.",
  question:"Para los países productores de petróleo, esa situación representó:",
  options:["Una caída fuerte de ingresos sin poder reducir la producción con rapidez.",
           "Una ganancia extra, porque vendieron más barriles al precio más alto del mercado.",
           "Un aumento de la producción para compensar el precio bajo con volumen.",
           "Un mercado estable, porque la oferta apenas cambió con el precio del barril."],
  answer:0,
  explanation:"Con oferta inelástica, los productores no pueden reducir su producción ante la caída del precio: sus ingresos cayeron con el precio. Es la vulnerabilidad del productor (la contracara de la ventaja de julio)."}
];
